### PR TITLE
feat: bulk workspace and purge-force

### PR DESCRIPTION
**Pull request by forstermatth**
* allows for `git bulk -w autovance purge` which executes the purge
command on all repos in the autovance folder

### CODE REVIEW

**Comment by trs** [comment]
@forstermatth Sorry for my lack of understanding, but what does `purge` do?

**Comment by forstermatth** [comment]
@trs https://github.com/autovance/dotfiles/commit/dbfbdbd553e51b8f99f383a54b7c958a1e36e133

**Comment by trs** [comment]
So this deletes merged branches?

**Comment by forstermatth** [comment]
It deletes merged branches locally, yes.

**Pull request merged**
