### PR TITLE
feat: allow remote branch checkout

### PR DESCRIPTION
**Pull request by trs**
Makes it easy to check out a remote branch:

```
$ g co username:branchname
```
If no `:` is specified, will act the same as before.

----

This does replace the current `co` command, but I'm down to make it it's own if you feel that's better.

### CODE REVIEW

**Comment by forstermatth** [comment]
Can you give an example scenario where this would be used? Is this for forks that have an `upstream` setup?

**Comment by trs** [comment]
It would be used when someone forks your repo. This lets you check out one of their branches.

I used it with `ftp-srv` when someone made a PR. I checked out their branch and renamed the commit to match the semantic releasing.

So it's really only useful in open source PRs from others. That's why I'm open to it being its own command.

**Comment by forstermatth** [comment]
`g cor` (checkout remote) or `g gof` (checkout fork)?

**Comment by Jl14Salvador** [comment]
Yeah I'd be in favor for the separate command. Either works.

**Pull request merged**
