### PR TITLE
chore(gitignore): remove reports from gitignore

### PR DESCRIPTION
**Pull request by Jl14Salvador**
**Chore**: 
- this allows the new reports service and Vader route to not be ignored in core

### CODE REVIEW

**Comment by Jl14Salvador** [comment]
The issue with calling the new microservice reports is that now we will have to add a local reports .gitignore file in any service or repo that has reports generated by our tests

**Comment by Jl14Salvador** [comment]
@trs @forstermatth  I'd like to come up with a decision for this. Therefore we can move forward with the new reports microservice.

**Comment by forstermatth** [comment]
Lets replace it with `build-reports/`

**Comment by trs** [comment]
Do we need a global ignore for this when it's just for the one repo. I feel we can just have the `.gitignore` in core, and not globally ignore things that may not be needed.

**Comment by forstermatth** [comment]
Fair, that's a good point.

**Comment by trs** [comment]
We might even be able to trim this down more since many entries seem specific to certain setups.

**Pull request merged**
